/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.template;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    /**
     * “ñ‚Â‚Ì®”‚Ì‡Œv‚ğ•Ô‚µ‚Ü‚·
     * @param a ˆø”1
     * @param b ˆø”2
     * @return ˆø”‚Ì‡Œv’l
     */
    public int addNum(final int a, final int b) {
        return a+b;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().addNum(1, 2));
    }
}
