/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.template;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();
    @Test void appHasAGreeting() {
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void testAddNum() {
        assertEquals(3, classUnderTest.addNum(1, 2));
    }
}
